const drugData = (addedBy) => {
  const drugs = [
    {
      drugId: 'DRG000001',
      name: 'Amoxicillin',
      genericName: 'Amoxicillin',
      brandName: 'Amoxil',
      category: 'Antibiotic',
      subCategory: 'Penicillin',
      therapeuticClass: 'Beta-lactam antibiotic',
      formulation: 'Capsule',
      strength: {
        value: 500,
        unit: 'mg',
      },
      manufacturer: {
        name: 'GlaxoSmithKline',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: true,
      isControlled: false,
      stock: {
        quantity: 500,
        unit: 'capsules',
        reorderLevel: 100,
        maxStockLevel: 1000,
      },
      pricing: {
        costPrice: 0.50,
        sellingPrice: 1.00,
        mrp: 1.20,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'AMX2024001',
          quantity: 500,
          manufactureDate: new Date('2024-01-01'),
          expiryDate: new Date('2026-01-01'),
          supplier: 'MediSupply Inc.',
          costPrice: 0.50,
          receivedDate: new Date('2024-01-15'),
        },
      ],
      description: 'Broad-spectrum antibiotic used to treat bacterial infections',
      sideEffects: ['Nausea', 'Diarrhea', 'Rash'],
      contraindications: ['Penicillin allergy'],
      interactions: ['Warfarin', 'Methotrexate'],
      dosageInstructions: 'Take with or without food',
      barcode: '1234567890001',
      sku: 'AMX-500-CAP',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000002',
      name: 'Paracetamol',
      genericName: 'Acetaminophen',
      brandName: 'Tylenol',
      category: 'Analgesic',
      subCategory: 'Non-opioid',
      therapeuticClass: 'Analgesic and antipyretic',
      formulation: 'Tablet',
      strength: {
        value: 500,
        unit: 'mg',
      },
      manufacturer: {
        name: 'Johnson & Johnson',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: false,
      isControlled: false,
      stock: {
        quantity: 1000,
        unit: 'tablets',
        reorderLevel: 200,
        maxStockLevel: 2000,
      },
      pricing: {
        costPrice: 0.10,
        sellingPrice: 0.25,
        mrp: 0.30,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'PAR2024001',
          quantity: 1000,
          manufactureDate: new Date('2024-02-01'),
          expiryDate: new Date('2027-02-01'),
          supplier: 'PharmaDist Co.',
          costPrice: 0.10,
          receivedDate: new Date('2024-02-10'),
        },
      ],
      description: 'Pain reliever and fever reducer',
      sideEffects: ['Liver damage (in overdose)', 'Allergic reactions'],
      contraindications: ['Severe liver disease'],
      interactions: ['Warfarin'],
      dosageInstructions: 'Take with water. Do not exceed 4g per day',
      barcode: '1234567890002',
      sku: 'PAR-500-TAB',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000003',
      name: 'Metformin',
      genericName: 'Metformin HCL',
      brandName: 'Glucophage',
      category: 'Antidiabetic',
      subCategory: 'Biguanide',
      therapeuticClass: 'Oral hypoglycemic agent',
      formulation: 'Tablet',
      strength: {
        value: 500,
        unit: 'mg',
      },
      manufacturer: {
        name: 'Bristol-Myers Squibb',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: true,
      isControlled: false,
      stock: {
        quantity: 750,
        unit: 'tablets',
        reorderLevel: 150,
        maxStockLevel: 1500,
      },
      pricing: {
        costPrice: 0.30,
        sellingPrice: 0.75,
        mrp: 0.90,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'MET2024001',
          quantity: 750,
          manufactureDate: new Date('2024-01-15'),
          expiryDate: new Date('2026-01-15'),
          supplier: 'MediSupply Inc.',
          costPrice: 0.30,
          receivedDate: new Date('2024-01-20'),
        },
      ],
      description: 'Used to treat type 2 diabetes',
      sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain'],
      contraindications: ['Renal impairment', 'Lactic acidosis'],
      interactions: ['Contrast media', 'Alcohol'],
      dosageInstructions: 'Take with meals',
      barcode: '1234567890003',
      sku: 'MET-500-TAB',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000004',
      name: 'Lisinopril',
      genericName: 'Lisinopril',
      brandName: 'Prinivil',
      category: 'Antihypertensive',
      subCategory: 'ACE Inhibitor',
      therapeuticClass: 'Angiotensin-converting enzyme inhibitor',
      formulation: 'Tablet',
      strength: {
        value: 10,
        unit: 'mg',
      },
      manufacturer: {
        name: 'Merck',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: true,
      isControlled: false,
      stock: {
        quantity: 600,
        unit: 'tablets',
        reorderLevel: 120,
        maxStockLevel: 1200,
      },
      pricing: {
        costPrice: 0.40,
        sellingPrice: 1.00,
        mrp: 1.20,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'LIS2024001',
          quantity: 600,
          manufactureDate: new Date('2024-02-01'),
          expiryDate: new Date('2026-02-01'),
          supplier: 'PharmaDist Co.',
          costPrice: 0.40,
          receivedDate: new Date('2024-02-05'),
        },
      ],
      description: 'Used to treat high blood pressure and heart failure',
      sideEffects: ['Dizziness', 'Dry cough', 'Headache'],
      contraindications: ['Pregnancy', 'Angioedema'],
      interactions: ['Potassium supplements', 'NSAIDs'],
      dosageInstructions: 'Take once daily at the same time',
      barcode: '1234567890004',
      sku: 'LIS-10-TAB',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000005',
      name: 'Omeprazole',
      genericName: 'Omeprazole',
      brandName: 'Prilosec',
      category: 'Antacid',
      subCategory: 'Proton Pump Inhibitor',
      therapeuticClass: 'Gastric acid suppression',
      formulation: 'Capsule',
      strength: {
        value: 20,
        unit: 'mg',
      },
      manufacturer: {
        name: 'AstraZeneca',
        country: 'UK',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: true,
      isControlled: false,
      stock: {
        quantity: 450,
        unit: 'capsules',
        reorderLevel: 90,
        maxStockLevel: 900,
      },
      pricing: {
        costPrice: 0.60,
        sellingPrice: 1.50,
        mrp: 1.80,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'OME2024001',
          quantity: 450,
          manufactureDate: new Date('2024-01-20'),
          expiryDate: new Date('2026-01-20'),
          supplier: 'MediSupply Inc.',
          costPrice: 0.60,
          receivedDate: new Date('2024-01-25'),
        },
      ],
      description: 'Reduces stomach acid production',
      sideEffects: ['Headache', 'Nausea', 'Abdominal pain'],
      contraindications: ['Hypersensitivity to PPIs'],
      interactions: ['Clopidogrel', 'Warfarin'],
      dosageInstructions: 'Take before breakfast',
      barcode: '1234567890005',
      sku: 'OME-20-CAP',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000006',
      name: 'Aspirin',
      genericName: 'Acetylsalicylic Acid',
      brandName: 'Bayer Aspirin',
      category: 'Analgesic',
      subCategory: 'NSAID',
      therapeuticClass: 'Anti-inflammatory and antiplatelet',
      formulation: 'Tablet',
      strength: {
        value: 75,
        unit: 'mg',
      },
      manufacturer: {
        name: 'Bayer',
        country: 'Germany',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: false,
      isControlled: false,
      stock: {
        quantity: 800,
        unit: 'tablets',
        reorderLevel: 160,
        maxStockLevel: 1600,
      },
      pricing: {
        costPrice: 0.05,
        sellingPrice: 0.15,
        mrp: 0.20,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'ASP2024001',
          quantity: 800,
          manufactureDate: new Date('2024-02-10'),
          expiryDate: new Date('2027-02-10'),
          supplier: 'PharmaDist Co.',
          costPrice: 0.05,
          receivedDate: new Date('2024-02-15'),
        },
      ],
      description: 'Used for pain relief and cardiovascular protection',
      sideEffects: ['Stomach upset', 'Bleeding', 'Ulcers'],
      contraindications: ['Bleeding disorders', 'Active ulcers'],
      interactions: ['Warfarin', 'NSAIDs'],
      dosageInstructions: 'Take with food or milk',
      barcode: '1234567890006',
      sku: 'ASP-75-TAB',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000007',
      name: 'Albuterol',
      genericName: 'Albuterol Sulfate',
      brandName: 'Ventolin',
      category: 'Antihistamine',
      subCategory: 'Bronchodilator',
      therapeuticClass: 'Beta-2 agonist',
      formulation: 'Inhaler',
      strength: {
        value: 100,
        unit: 'mcg',
      },
      manufacturer: {
        name: 'GlaxoSmithKline',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: true,
      isControlled: false,
      stock: {
        quantity: 200,
        unit: 'inhalers',
        reorderLevel: 40,
        maxStockLevel: 400,
      },
      pricing: {
        costPrice: 25.00,
        sellingPrice: 50.00,
        mrp: 60.00,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'ALB2024001',
          quantity: 200,
          manufactureDate: new Date('2024-01-05'),
          expiryDate: new Date('2025-01-05'),
          supplier: 'MediSupply Inc.',
          costPrice: 25.00,
          receivedDate: new Date('2024-01-10'),
        },
      ],
      description: 'Quick-relief inhaler for asthma and COPD',
      sideEffects: ['Tremor', 'Nervousness', 'Rapid heartbeat'],
      contraindications: ['Severe heart disease'],
      interactions: ['Beta-blockers', 'MAO inhibitors'],
      dosageInstructions: 'Shake well before use. Inhale as directed',
      barcode: '1234567890007',
      sku: 'ALB-100-INH',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000008',
      name: 'Ibuprofen',
      genericName: 'Ibuprofen',
      brandName: 'Advil',
      category: 'Analgesic',
      subCategory: 'NSAID',
      therapeuticClass: 'Non-steroidal anti-inflammatory drug',
      formulation: 'Tablet',
      strength: {
        value: 400,
        unit: 'mg',
      },
      manufacturer: {
        name: 'Pfizer',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: false,
      isControlled: false,
      stock: {
        quantity: 900,
        unit: 'tablets',
        reorderLevel: 180,
        maxStockLevel: 1800,
      },
      pricing: {
        costPrice: 0.15,
        sellingPrice: 0.35,
        mrp: 0.45,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'IBU2024001',
          quantity: 900,
          manufactureDate: new Date('2024-02-01'),
          expiryDate: new Date('2027-02-01'),
          supplier: 'PharmaDist Co.',
          costPrice: 0.15,
          receivedDate: new Date('2024-02-05'),
        },
      ],
      description: 'Pain reliever and anti-inflammatory',
      sideEffects: ['Stomach upset', 'Dizziness', 'Heartburn'],
      contraindications: ['Active ulcers', 'Severe heart failure'],
      interactions: ['Aspirin', 'Warfarin', 'ACE inhibitors'],
      dosageInstructions: 'Take with food or milk',
      barcode: '1234567890008',
      sku: 'IBU-400-TAB',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000009',
      name: 'Cetirizine',
      genericName: 'Cetirizine HCL',
      brandName: 'Zyrtec',
      category: 'Antihistamine',
      subCategory: 'H1 Antagonist',
      therapeuticClass: 'Second-generation antihistamine',
      formulation: 'Tablet',
      strength: {
        value: 10,
        unit: 'mg',
      },
      manufacturer: {
        name: 'UCB Pharma',
        country: 'Belgium',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: false,
      isControlled: false,
      stock: {
        quantity: 600,
        unit: 'tablets',
        reorderLevel: 120,
        maxStockLevel: 1200,
      },
      pricing: {
        costPrice: 0.20,
        sellingPrice: 0.50,
        mrp: 0.60,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'CET2024001',
          quantity: 600,
          manufactureDate: new Date('2024-01-10'),
          expiryDate: new Date('2027-01-10'),
          supplier: 'MediSupply Inc.',
          costPrice: 0.20,
          receivedDate: new Date('2024-01-15'),
        },
      ],
      description: 'Allergy relief medication',
      sideEffects: ['Drowsiness', 'Dry mouth', 'Fatigue'],
      contraindications: ['Severe kidney disease'],
      interactions: ['Alcohol', 'CNS depressants'],
      dosageInstructions: 'Take once daily, with or without food',
      barcode: '1234567890009',
      sku: 'CET-10-TAB',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
    {
      drugId: 'DRG000010',
      name: 'Vitamin D3',
      genericName: 'Cholecalciferol',
      brandName: 'D3-50',
      category: 'Vitamin',
      subCategory: 'Fat-soluble vitamin',
      therapeuticClass: 'Vitamin supplement',
      formulation: 'Capsule',
      strength: {
        value: 1000,
        unit: 'IU',
      },
      manufacturer: {
        name: 'Nature Made',
        country: 'USA',
      },
      storageConditions: 'Store at room temperature',
      requiresRefrigeration: false,
      requiresPrescription: false,
      isControlled: false,
      stock: {
        quantity: 1200,
        unit: 'capsules',
        reorderLevel: 240,
        maxStockLevel: 2400,
      },
      pricing: {
        costPrice: 0.08,
        sellingPrice: 0.20,
        mrp: 0.25,
        discount: 0,
      },
      batches: [
        {
          batchNumber: 'VD32024001',
          quantity: 1200,
          manufactureDate: new Date('2024-01-01'),
          expiryDate: new Date('2026-01-01'),
          supplier: 'PharmaDist Co.',
          costPrice: 0.08,
          receivedDate: new Date('2024-01-05'),
        },
      ],
      description: 'Vitamin D supplement for bone health',
      sideEffects: ['Nausea (rare)', 'Constipation (rare)'],
      contraindications: ['Hypercalcemia'],
      interactions: ['Thiazide diuretics'],
      dosageInstructions: 'Take once daily with food',
      barcode: '1234567890010',
      sku: 'VD3-1000-CAP',
      isActive: true,
      isAvailable: true,
      addedBy,
    },
  ];

  return drugs;
};

module.exports = drugData;
