const patientData = (registeredBy) => {
  const patients = [
    {
      patientId: 'PAT000001',
      firstName: 'John',
      lastName: 'Smith',
      email: 'john.smith@email.com',
      phone: '+1234568001',
      alternatePhone: '+1234568002',
      dateOfBirth: new Date('1975-05-15'),
      gender: 'Male',
      bloodGroup: 'O+',
      maritalStatus: 'Married',
      nationality: 'American',
      occupation: 'Software Engineer',
      address: {
        street: '123 Patient Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10001',
      },
      emergencyContact: {
        name: 'Mary Smith',
        relationship: 'Wife',
        phone: '+1234568003',
      },
      allergies: [
        {
          allergen: 'Penicillin',
          severity: 'Severe',
          reaction: 'Anaphylaxis',
        },
      ],
      chronicConditions: [
        {
          condition: 'Hypertension',
          diagnosedDate: new Date('2018-03-10'),
          status: 'Controlled',
        },
      ],
      insurance: {
        provider: 'Blue Cross Blue Shield',
        policyNumber: 'BCBS123456',
        groupNumber: 'GRP001',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Family',
        coverageAmount: 500000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-01-15'),
    },
    {
      patientId: 'PAT000002',
      firstName: 'Emma',
      lastName: 'Johnson',
      email: 'emma.johnson@email.com',
      phone: '+1234568004',
      dateOfBirth: new Date('1990-08-22'),
      gender: 'Female',
      bloodGroup: 'A+',
      maritalStatus: 'Single',
      nationality: 'American',
      occupation: 'Teacher',
      address: {
        street: '456 Oak Avenue',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10002',
      },
      emergencyContact: {
        name: 'Robert Johnson',
        relationship: 'Father',
        phone: '+1234568005',
      },
      allergies: [
        {
          allergen: 'Peanuts',
          severity: 'Moderate',
          reaction: 'Hives and swelling',
        },
      ],
      chronicConditions: [],
      insurance: {
        provider: 'Aetna',
        policyNumber: 'AET789012',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Individual',
        coverageAmount: 250000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-02-10'),
    },
    {
      patientId: 'PAT000003',
      firstName: 'Michael',
      lastName: 'Davis',
      email: 'michael.davis@email.com',
      phone: '+1234568006',
      dateOfBirth: new Date('1965-12-03'),
      gender: 'Male',
      bloodGroup: 'B+',
      maritalStatus: 'Married',
      nationality: 'American',
      occupation: 'Retired',
      address: {
        street: '789 Pine Road',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10003',
      },
      emergencyContact: {
        name: 'Sarah Davis',
        relationship: 'Wife',
        phone: '+1234568007',
      },
      allergies: [],
      chronicConditions: [
        {
          condition: 'Type 2 Diabetes',
          diagnosedDate: new Date('2015-06-20'),
          status: 'Active',
        },
        {
          condition: 'High Cholesterol',
          diagnosedDate: new Date('2016-09-15'),
          status: 'Controlled',
        },
      ],
      insurance: {
        provider: 'Medicare',
        policyNumber: 'MED345678',
        validFrom: new Date('2020-01-01'),
        validUntil: new Date('2025-12-31'),
        coverageType: 'Individual',
        coverageAmount: 100000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-03-05'),
    },
    {
      patientId: 'PAT000004',
      firstName: 'Sophia',
      lastName: 'Martinez',
      email: 'sophia.martinez@email.com',
      phone: '+1234568008',
      dateOfBirth: new Date('2015-04-18'),
      gender: 'Female',
      bloodGroup: 'AB+',
      maritalStatus: 'Single',
      nationality: 'American',
      occupation: 'Student',
      address: {
        street: '321 Maple Drive',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10004',
      },
      emergencyContact: {
        name: 'Maria Martinez',
        relationship: 'Mother',
        phone: '+1234568009',
      },
      allergies: [
        {
          allergen: 'Eggs',
          severity: 'Mild',
          reaction: 'Skin rash',
        },
      ],
      chronicConditions: [
        {
          condition: 'Asthma',
          diagnosedDate: new Date('2018-11-10'),
          status: 'Active',
        },
      ],
      insurance: {
        provider: 'UnitedHealthcare',
        policyNumber: 'UHC567890',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Family',
        coverageAmount: 300000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-04-12'),
    },
    {
      patientId: 'PAT000005',
      firstName: 'William',
      lastName: 'Anderson',
      email: 'william.anderson@email.com',
      phone: '+1234568010',
      dateOfBirth: new Date('1982-07-30'),
      gender: 'Male',
      bloodGroup: 'O-',
      maritalStatus: 'Divorced',
      nationality: 'American',
      occupation: 'Accountant',
      address: {
        street: '654 Elm Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10005',
      },
      emergencyContact: {
        name: 'James Anderson',
        relationship: 'Brother',
        phone: '+1234568011',
      },
      allergies: [],
      chronicConditions: [],
      insurance: {
        provider: 'Cigna',
        policyNumber: 'CIG901234',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Individual',
        coverageAmount: 200000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-05-20'),
    },
    {
      patientId: 'PAT000006',
      firstName: 'Olivia',
      lastName: 'Taylor',
      email: 'olivia.taylor@email.com',
      phone: '+1234568012',
      dateOfBirth: new Date('1995-11-08'),
      gender: 'Female',
      bloodGroup: 'A-',
      maritalStatus: 'Single',
      nationality: 'American',
      occupation: 'Graphic Designer',
      address: {
        street: '987 Cedar Lane',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10006',
      },
      emergencyContact: {
        name: 'Jennifer Taylor',
        relationship: 'Mother',
        phone: '+1234568013',
      },
      allergies: [
        {
          allergen: 'Latex',
          severity: 'Moderate',
          reaction: 'Contact dermatitis',
        },
      ],
      chronicConditions: [],
      insurance: {
        provider: 'Humana',
        policyNumber: 'HUM234567',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Individual',
        coverageAmount: 150000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-06-15'),
    },
    {
      patientId: 'PAT000007',
      firstName: 'James',
      lastName: 'Wilson',
      email: 'james.wilson@email.com',
      phone: '+1234568014',
      dateOfBirth: new Date('1978-02-14'),
      gender: 'Male',
      bloodGroup: 'B-',
      maritalStatus: 'Married',
      nationality: 'American',
      occupation: 'Construction Worker',
      address: {
        street: '147 Birch Avenue',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10007',
      },
      emergencyContact: {
        name: 'Lisa Wilson',
        relationship: 'Wife',
        phone: '+1234568015',
      },
      allergies: [],
      chronicConditions: [
        {
          condition: 'Chronic Back Pain',
          diagnosedDate: new Date('2019-08-25'),
          status: 'Active',
        },
      ],
      insurance: {
        provider: 'Kaiser Permanente',
        policyNumber: 'KP345678',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Family',
        coverageAmount: 400000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-07-22'),
    },
    {
      patientId: 'PAT000008',
      firstName: 'Isabella',
      lastName: 'Brown',
      email: 'isabella.brown@email.com',
      phone: '+1234568016',
      dateOfBirth: new Date('2010-09-27'),
      gender: 'Female',
      bloodGroup: 'AB-',
      maritalStatus: 'Single',
      nationality: 'American',
      occupation: 'Student',
      address: {
        street: '258 Willow Road',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10008',
      },
      emergencyContact: {
        name: 'Patricia Brown',
        relationship: 'Mother',
        phone: '+1234568017',
      },
      allergies: [
        {
          allergen: 'Shellfish',
          severity: 'Severe',
          reaction: 'Anaphylaxis',
        },
      ],
      chronicConditions: [],
      insurance: {
        provider: 'Blue Cross Blue Shield',
        policyNumber: 'BCBS789012',
        validFrom: new Date('2023-01-01'),
        validUntil: new Date('2024-12-31'),
        coverageType: 'Family',
        coverageAmount: 350000,
      },
      status: 'Active',
      registeredBy,
      registrationDate: new Date('2023-08-30'),
    },
  ];

  return patients;
};

module.exports = patientData;
