const bcrypt = require('bcryptjs');

// Helper function to hash password
const hashPassword = async (password) => {
  return await bcrypt.hash(password, 12);
};

// Staff data for all roles
const staffData = async () => {
  const defaultPassword = await hashPassword('password123');

  return [
    // 1. Super Admin
    {
      firstName: 'Super',
      lastName: 'Admin',
      email: 'superadmin@hospital.com',
      password: defaultPassword,
      phone: '+1234567001',
      dateOfBirth: new Date('1985-01-15'),
      gender: 'Male',
      bloodGroup: 'O+',
      maritalStatus: 'Married',
      address: {
        street: '123 Admin Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10001',
      },
      employeeId: 'EMP001',
      department: 'Administration',
      designation: 'System Administrator',
      role: 'Super Admin',
      joiningDate: new Date('2020-01-01'),
      employmentType: 'Permanent',
      salary: 120000,
      isActive: true,
      status: 'Active',
      permissions: ['all'],
      emergencyContact: {
        name: 'Jane Admin',
        relationship: 'Spouse',
        phone: '+1234567002',
      },
    },

    // 2. Admin
    {
      firstName: 'John',
      lastName: 'Administrator',
      email: 'admin@hospital.com',
      password: defaultPassword,
      phone: '+1234567003',
      dateOfBirth: new Date('1988-03-20'),
      gender: 'Male',
      bloodGroup: 'A+',
      maritalStatus: 'Single',
      address: {
        street: '456 Admin Avenue',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10002',
      },
      employeeId: 'EMP002',
      department: 'Administration',
      designation: 'Administrator',
      role: 'Admin',
      joiningDate: new Date('2020-06-01'),
      employmentType: 'Permanent',
      salary: 95000,
      isActive: true,
      status: 'Active',
      permissions: ['manage_users', 'view_reports', 'manage_departments'],
      emergencyContact: {
        name: 'Mary Administrator',
        relationship: 'Sister',
        phone: '+1234567004',
      },
    },

    // 3. Doctor - Cardiologist
    {
      firstName: 'Sarah',
      lastName: 'Johnson',
      email: 'sarah.johnson@hospital.com',
      password: defaultPassword,
      phone: '+1234567005',
      dateOfBirth: new Date('1982-07-10'),
      gender: 'Female',
      bloodGroup: 'B+',
      maritalStatus: 'Married',
      address: {
        street: '789 Medical Plaza',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10003',
      },
      employeeId: 'DOC001',
      department: 'Medical',
      designation: 'Senior Cardiologist',
      role: 'Doctor',
      joiningDate: new Date('2018-03-15'),
      employmentType: 'Permanent',
      salary: 150000,
      isActive: true,
      status: 'Active',
      specialization: 'Cardiology',
      qualifications: ['MBBS', 'MD Cardiology', 'FACC'],
      experience: 15,
      languages: ['English', 'Spanish'],
      permissions: ['view_patients', 'prescribe', 'view_lab_results'],
      emergencyContact: {
        name: 'Michael Johnson',
        relationship: 'Husband',
        phone: '+1234567006',
      },
    },

    // 4. Doctor - General Medicine
    {
      firstName: 'David',
      lastName: 'Williams',
      email: 'david.williams@hospital.com',
      password: defaultPassword,
      phone: '+1234567007',
      dateOfBirth: new Date('1980-05-25'),
      gender: 'Male',
      bloodGroup: 'AB+',
      maritalStatus: 'Married',
      address: {
        street: '321 Health Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10004',
      },
      employeeId: 'DOC002',
      department: 'Medical',
      designation: 'General Physician',
      role: 'Doctor',
      joiningDate: new Date('2019-01-10'),
      employmentType: 'Permanent',
      salary: 140000,
      isActive: true,
      status: 'Active',
      specialization: 'General Medicine',
      qualifications: ['MBBS', 'MD General Medicine'],
      experience: 12,
      languages: ['English'],
      permissions: ['view_patients', 'prescribe', 'view_lab_results'],
      emergencyContact: {
        name: 'Lisa Williams',
        relationship: 'Wife',
        phone: '+1234567008',
      },
    },

    // 5. Doctor - Pediatrician
    {
      firstName: 'Emily',
      lastName: 'Brown',
      email: 'emily.brown@hospital.com',
      password: defaultPassword,
      phone: '+1234567009',
      dateOfBirth: new Date('1986-09-12'),
      gender: 'Female',
      bloodGroup: 'O-',
      maritalStatus: 'Single',
      address: {
        street: '555 Care Lane',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10005',
      },
      employeeId: 'DOC003',
      department: 'Medical',
      designation: 'Pediatrician',
      role: 'Doctor',
      joiningDate: new Date('2019-08-20'),
      employmentType: 'Permanent',
      salary: 135000,
      isActive: true,
      status: 'Active',
      specialization: 'Pediatrics',
      qualifications: ['MBBS', 'MD Pediatrics'],
      experience: 10,
      languages: ['English', 'French'],
      permissions: ['view_patients', 'prescribe', 'view_lab_results'],
      emergencyContact: {
        name: 'Robert Brown',
        relationship: 'Father',
        phone: '+1234567010',
      },
    },

    // 6. Nurse - Head Nurse
    {
      firstName: 'Maria',
      lastName: 'Garcia',
      email: 'maria.garcia@hospital.com',
      password: defaultPassword,
      phone: '+1234567011',
      dateOfBirth: new Date('1990-04-18'),
      gender: 'Female',
      bloodGroup: 'A-',
      maritalStatus: 'Married',
      address: {
        street: '888 Nursing Road',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10006',
      },
      employeeId: 'NUR001',
      department: 'Nursing',
      designation: 'Head Nurse',
      role: 'Nurse',
      joiningDate: new Date('2017-05-10'),
      employmentType: 'Permanent',
      salary: 75000,
      isActive: true,
      status: 'Active',
      qualifications: ['BSN', 'RN'],
      experience: 8,
      languages: ['English', 'Spanish'],
      permissions: ['view_patients', 'update_vitals', 'view_schedules'],
      emergencyContact: {
        name: 'Carlos Garcia',
        relationship: 'Husband',
        phone: '+1234567012',
      },
    },

    // 7. Nurse - ICU Nurse
    {
      firstName: 'Jennifer',
      lastName: 'Martinez',
      email: 'jennifer.martinez@hospital.com',
      password: defaultPassword,
      phone: '+1234567013',
      dateOfBirth: new Date('1992-11-22'),
      gender: 'Female',
      bloodGroup: 'B-',
      maritalStatus: 'Single',
      address: {
        street: '999 ICU Boulevard',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10007',
      },
      employeeId: 'NUR002',
      department: 'Nursing',
      designation: 'ICU Nurse',
      role: 'Nurse',
      joiningDate: new Date('2018-02-15'),
      employmentType: 'Permanent',
      salary: 70000,
      isActive: true,
      status: 'Active',
      qualifications: ['BSN', 'RN', 'CCRN'],
      experience: 6,
      languages: ['English'],
      permissions: ['view_patients', 'update_vitals', 'emergency_care'],
      emergencyContact: {
        name: 'Anna Martinez',
        relationship: 'Mother',
        phone: '+1234567014',
      },
    },

    // 8. Pharmacist
    {
      firstName: 'Robert',
      lastName: 'Taylor',
      email: 'robert.taylor@hospital.com',
      password: defaultPassword,
      phone: '+1234567015',
      dateOfBirth: new Date('1987-06-30'),
      gender: 'Male',
      bloodGroup: 'O+',
      maritalStatus: 'Married',
      address: {
        street: '111 Pharmacy Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10008',
      },
      employeeId: 'PHA001',
      department: 'Pharmacy',
      designation: 'Chief Pharmacist',
      role: 'Pharmacist',
      joiningDate: new Date('2016-09-01'),
      employmentType: 'Permanent',
      salary: 85000,
      isActive: true,
      status: 'Active',
      qualifications: ['PharmD', 'RPh'],
      experience: 11,
      languages: ['English'],
      permissions: ['manage_inventory', 'dispense_medication', 'view_prescriptions'],
      emergencyContact: {
        name: 'Susan Taylor',
        relationship: 'Wife',
        phone: '+1234567016',
      },
    },

    // 9. Lab Technician
    {
      firstName: 'Michael',
      lastName: 'Anderson',
      email: 'michael.anderson@hospital.com',
      password: defaultPassword,
      phone: '+1234567017',
      dateOfBirth: new Date('1991-08-14'),
      gender: 'Male',
      bloodGroup: 'A+',
      maritalStatus: 'Single',
      address: {
        street: '222 Lab Avenue',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10009',
      },
      employeeId: 'LAB001',
      department: 'Laboratory',
      designation: 'Senior Lab Technician',
      role: 'Lab Technician',
      joiningDate: new Date('2018-07-20'),
      employmentType: 'Permanent',
      salary: 65000,
      isActive: true,
      status: 'Active',
      qualifications: ['BS Medical Technology', 'MT(ASCP)'],
      experience: 7,
      languages: ['English'],
      permissions: ['process_samples', 'enter_results', 'view_test_requests'],
      emergencyContact: {
        name: 'Patricia Anderson',
        relationship: 'Mother',
        phone: '+1234567018',
      },
    },

    // 10. Radiologist
    {
      firstName: 'James',
      lastName: 'Wilson',
      email: 'james.wilson@hospital.com',
      password: defaultPassword,
      phone: '+1234567019',
      dateOfBirth: new Date('1983-12-05'),
      gender: 'Male',
      bloodGroup: 'B+',
      maritalStatus: 'Married',
      address: {
        street: '333 Radiology Drive',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10010',
      },
      employeeId: 'RAD001',
      department: 'Radiology',
      designation: 'Chief Radiologist',
      role: 'Radiologist',
      joiningDate: new Date('2017-11-15'),
      employmentType: 'Permanent',
      salary: 145000,
      isActive: true,
      status: 'Active',
      qualifications: ['MBBS', 'MD Radiology', 'FRCR'],
      experience: 13,
      languages: ['English'],
      permissions: ['view_imaging', 'generate_reports', 'request_imaging'],
      emergencyContact: {
        name: 'Helen Wilson',
        relationship: 'Wife',
        phone: '+1234567020',
      },
    },

    // 11. Receptionist
    {
      firstName: 'Amanda',
      lastName: 'Moore',
      email: 'amanda.moore@hospital.com',
      password: defaultPassword,
      phone: '+1234567021',
      dateOfBirth: new Date('1995-02-28'),
      gender: 'Female',
      bloodGroup: 'O-',
      maritalStatus: 'Single',
      address: {
        street: '444 Front Desk Lane',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10011',
      },
      employeeId: 'REC001',
      department: 'Administration',
      designation: 'Senior Receptionist',
      role: 'Receptionist',
      joiningDate: new Date('2019-04-10'),
      employmentType: 'Permanent',
      salary: 45000,
      isActive: true,
      status: 'Active',
      qualifications: ['High School Diploma', 'Customer Service Certification'],
      experience: 4,
      languages: ['English', 'Spanish'],
      permissions: ['register_patients', 'schedule_appointments', 'check_in'],
      emergencyContact: {
        name: 'Linda Moore',
        relationship: 'Mother',
        phone: '+1234567022',
      },
    },

    // 12. Accountant
    {
      firstName: 'Richard',
      lastName: 'Thomas',
      email: 'richard.thomas@hospital.com',
      password: defaultPassword,
      phone: '+1234567023',
      dateOfBirth: new Date('1984-10-17'),
      gender: 'Male',
      bloodGroup: 'AB-',
      maritalStatus: 'Married',
      address: {
        street: '555 Finance Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10012',
      },
      employeeId: 'ACC001',
      department: 'Billing',
      designation: 'Senior Accountant',
      role: 'Accountant',
      joiningDate: new Date('2016-01-20'),
      employmentType: 'Permanent',
      salary: 80000,
      isActive: true,
      status: 'Active',
      qualifications: ['BBA', 'MBA Finance', 'CPA'],
      experience: 12,
      languages: ['English'],
      permissions: ['manage_billing', 'generate_invoices', 'view_payments'],
      emergencyContact: {
        name: 'Nancy Thomas',
        relationship: 'Wife',
        phone: '+1234567024',
      },
    },

    // 13. HR Manager
    {
      firstName: 'Patricia',
      lastName: 'Jackson',
      email: 'patricia.jackson@hospital.com',
      password: defaultPassword,
      phone: '+1234567025',
      dateOfBirth: new Date('1981-03-08'),
      gender: 'Female',
      bloodGroup: 'A+',
      maritalStatus: 'Married',
      address: {
        street: '666 HR Avenue',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10013',
      },
      employeeId: 'HR001',
      department: 'HR',
      designation: 'HR Manager',
      role: 'HR Manager',
      joiningDate: new Date('2015-06-15'),
      employmentType: 'Permanent',
      salary: 90000,
      isActive: true,
      status: 'Active',
      qualifications: ['BBA', 'MBA HR', 'SHRM-CP'],
      experience: 14,
      languages: ['English'],
      permissions: ['manage_staff', 'process_payroll', 'manage_leaves'],
      emergencyContact: {
        name: 'Daniel Jackson',
        relationship: 'Husband',
        phone: '+1234567026',
      },
    },

    // 14. IT Support
    {
      firstName: 'Christopher',
      lastName: 'White',
      email: 'christopher.white@hospital.com',
      password: defaultPassword,
      phone: '+1234567027',
      dateOfBirth: new Date('1993-07-21'),
      gender: 'Male',
      bloodGroup: 'B+',
      maritalStatus: 'Single',
      address: {
        street: '777 Tech Drive',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10014',
      },
      employeeId: 'IT001',
      department: 'IT',
      designation: 'IT Support Specialist',
      role: 'IT Support',
      joiningDate: new Date('2020-02-10'),
      employmentType: 'Permanent',
      salary: 70000,
      isActive: true,
      status: 'Active',
      qualifications: ['BS Computer Science', 'CompTIA A+', 'Network+'],
      experience: 5,
      languages: ['English'],
      permissions: ['system_access', 'technical_support', 'manage_backups'],
      emergencyContact: {
        name: 'Barbara White',
        relationship: 'Mother',
        phone: '+1234567028',
      },
    },

    // 15. Housekeeper
    {
      firstName: 'Jessica',
      lastName: 'Harris',
      email: 'jessica.harris@hospital.com',
      password: defaultPassword,
      phone: '+1234567029',
      dateOfBirth: new Date('1989-09-30'),
      gender: 'Female',
      bloodGroup: 'O+',
      maritalStatus: 'Married',
      address: {
        street: '888 Clean Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10015',
      },
      employeeId: 'HSK001',
      department: 'Housekeeping',
      designation: 'Housekeeping Supervisor',
      role: 'Housekeeper',
      joiningDate: new Date('2018-08-01'),
      employmentType: 'Permanent',
      salary: 42000,
      isActive: true,
      status: 'Active',
      qualifications: ['High School Diploma', 'Housekeeping Certification'],
      experience: 6,
      languages: ['English', 'Spanish'],
      permissions: ['view_schedules', 'submit_reports'],
      emergencyContact: {
        name: 'Mark Harris',
        relationship: 'Husband',
        phone: '+1234567030',
      },
    },

    // 16. Security
    {
      firstName: 'Kevin',
      lastName: 'Martin',
      email: 'kevin.martin@hospital.com',
      password: defaultPassword,
      phone: '+1234567031',
      dateOfBirth: new Date('1988-11-11'),
      gender: 'Male',
      bloodGroup: 'A-',
      maritalStatus: 'Single',
      address: {
        street: '999 Security Boulevard',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10016',
      },
      employeeId: 'SEC001',
      department: 'Security',
      designation: 'Security Officer',
      role: 'Security',
      joiningDate: new Date('2019-03-20'),
      employmentType: 'Permanent',
      salary: 48000,
      isActive: true,
      status: 'Active',
      qualifications: ['High School Diploma', 'Security License'],
      experience: 7,
      languages: ['English'],
      permissions: ['view_schedules', 'incident_reporting'],
      emergencyContact: {
        name: 'Dorothy Martin',
        relationship: 'Mother',
        phone: '+1234567032',
      },
    },

    // 17. Dietician
    {
      firstName: 'Laura',
      lastName: 'Thompson',
      email: 'laura.thompson@hospital.com',
      password: defaultPassword,
      phone: '+1234567033',
      dateOfBirth: new Date('1990-05-19'),
      gender: 'Female',
      bloodGroup: 'B-',
      maritalStatus: 'Married',
      address: {
        street: '101 Nutrition Lane',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10017',
      },
      employeeId: 'DIE001',
      department: 'Dietary',
      designation: 'Clinical Dietician',
      role: 'Dietician',
      joiningDate: new Date('2017-10-05'),
      employmentType: 'Permanent',
      salary: 68000,
      isActive: true,
      status: 'Active',
      qualifications: ['BS Nutrition', 'RD', 'CDN'],
      experience: 8,
      languages: ['English'],
      permissions: ['create_meal_plans', 'view_patients', 'dietary_consultations'],
      emergencyContact: {
        name: 'Steven Thompson',
        relationship: 'Husband',
        phone: '+1234567034',
      },
    },

    // 18. Cashier
    {
      firstName: 'Rachel',
      lastName: 'Martinez',
      email: 'rachel.martinez@hospital.com',
      password: defaultPassword,
      phone: '+1234567035',
      dateOfBirth: new Date('1992-06-18'),
      gender: 'Female',
      bloodGroup: 'A+',
      maritalStatus: 'Single',
      address: {
        street: '789 Billing Avenue',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10018',
      },
      employeeId: 'CASH001',
      department: 'Billing',
      designation: 'Senior Cashier',
      role: 'Cashier',
      joiningDate: new Date('2019-05-10'),
      employmentType: 'Permanent',
      salary: 52000,
      isActive: true,
      status: 'Active',
      qualifications: ['BS Accounting', 'Certified Medical Billing Specialist'],
      experience: 6,
      languages: ['English', 'Spanish'],
      permissions: [
        'create_patients',
        'view_patients',
        'update_patients',
        'view_appointments',
        'create_appointments',
        'manage_billing',
        'create_invoices',
        'process_payments',
        'view_financial_reports',
        'assign_beds',
      ],
      emergencyContact: {
        name: 'Carlos Martinez',
        relationship: 'Brother',
        phone: '+1234567036',
      },
    },
  ];
};

module.exports = staffData;
