const wardData = (nurseInChargeId) => {
  const wards = [
    {
      wardId: 'WARD001',
      name: 'General Ward A',
      type: 'General',
      floor: 1,
      totalBeds: 20,
      availableBeds: 20,
      beds: Array.from({ length: 20 }, (_, i) => ({
        bedNumber: `A${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD002',
      name: 'General Ward B',
      type: 'General',
      floor: 1,
      totalBeds: 20,
      availableBeds: 20,
      beds: Array.from({ length: 20 }, (_, i) => ({
        bedNumber: `B${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD003',
      name: 'ICU Ward',
      type: 'ICU',
      floor: 2,
      totalBeds: 10,
      availableBeds: 10,
      beds: Array.from({ length: 10 }, (_, i) => ({
        bedNumber: `ICU${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD004',
      name: 'CCU Ward',
      type: 'CCU',
      floor: 2,
      totalBeds: 8,
      availableBeds: 8,
      beds: Array.from({ length: 8 }, (_, i) => ({
        bedNumber: `CCU${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD005',
      name: 'Maternity Ward',
      type: 'Maternity',
      floor: 3,
      totalBeds: 15,
      availableBeds: 15,
      beds: Array.from({ length: 15 }, (_, i) => ({
        bedNumber: `MAT${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD006',
      name: 'Pediatric Ward',
      type: 'Pediatric',
      floor: 3,
      totalBeds: 12,
      availableBeds: 12,
      beds: Array.from({ length: 12 }, (_, i) => ({
        bedNumber: `PED${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD007',
      name: 'Emergency Ward',
      type: 'Emergency',
      floor: 0,
      totalBeds: 10,
      availableBeds: 10,
      beds: Array.from({ length: 10 }, (_, i) => ({
        bedNumber: `EMR${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
    {
      wardId: 'WARD008',
      name: 'Isolation Ward',
      type: 'Isolation',
      floor: 4,
      totalBeds: 6,
      availableBeds: 6,
      beds: Array.from({ length: 6 }, (_, i) => ({
        bedNumber: `ISO${String(i + 1).padStart(2, '0')}`,
        isOccupied: false,
        patient: null,
        admissionDate: null,
      })),
      nurseInCharge: nurseInChargeId,
      isActive: true,
    },
  ];

  return wards;
};

module.exports = wardData;
